stages:
  - build
  - docker
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/zmitiatef@gmail.com/example-app-microservice

# 🧱 Build Stage
build-job:
  stage: build
  image: maven:3.8.7-openjdk-11
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

# 🐳 Docker Build & Push
docker-job:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  needs: ["build-job"]

# 🚀 Deploy Job (Optional - you can SSH to your VPS or Kubernetes)
deploy-job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no user@your-vps-ip "docker pull $DOCKER_IMAGE:latest && docker run -d -p 8080:8080 $DOCKER_IMAGE:latest"
  only:
    - main
